"""update_models

Revision ID: dc499914860d
Revises: de00af206ce1
Create Date: 2025-09-05 12:01:40.048883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc499914860d'
down_revision: Union[str, Sequence[str], None] = 'de00af206ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('video_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_question_id'], ['video_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_question_answers_id'), 'video_question_answers', ['id'], unique=False)
    op.drop_constraint(op.f('student_results_rating_id_fkey'), 'student_results', type_='foreignkey')
    op.create_foreign_key(None, 'student_results', 'ratings', ['rating_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('students_direction_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'directions', ['direction_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('test_answers_test_id_fkey'), 'test_answers', type_='foreignkey')
    op.create_foreign_key(None, 'test_answers', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tests_direction_id_fkey'), 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'directions', ['direction_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('video_questions_video_id_fkey'), 'video_questions', type_='foreignkey')
    op.create_foreign_key(None, 'video_questions', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_column('video_questions', 'answer')
    op.drop_constraint(op.f('videos_rating_id_fkey'), 'videos', type_='foreignkey')
    op.drop_constraint(op.f('videos_direction_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'ratings', ['rating_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'videos', 'directions', ['direction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_direction_id_fkey'), 'videos', 'directions', ['direction_id'], ['id'])
    op.create_foreign_key(op.f('videos_rating_id_fkey'), 'videos', 'ratings', ['rating_id'], ['id'])
    op.add_column('video_questions', sa.Column('answer', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video_questions', type_='foreignkey')
    op.create_foreign_key(op.f('video_questions_video_id_fkey'), 'video_questions', 'videos', ['video_id'], ['id'])
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key(op.f('tests_direction_id_fkey'), 'tests', 'directions', ['direction_id'], ['id'])
    op.drop_constraint(None, 'test_answers', type_='foreignkey')
    op.create_foreign_key(op.f('test_answers_test_id_fkey'), 'test_answers', 'tests', ['test_id'], ['id'])
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_direction_id_fkey'), 'students', 'directions', ['direction_id'], ['id'])
    op.drop_constraint(None, 'student_results', type_='foreignkey')
    op.create_foreign_key(op.f('student_results_rating_id_fkey'), 'student_results', 'ratings', ['rating_id'], ['id'])
    op.drop_index(op.f('ix_video_question_answers_id'), table_name='video_question_answers')
    op.drop_table('video_question_answers')
    # ### end Alembic commands ###
